# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38a67cb19ba5d24b93daf6c49f6cc04f8ebec2920b7e72abc2ef15ffeb7e79880d46c8ca8f8e14965efc165dc5219d9c90e3b14e5060f2b31a5fda73b553bd48

test:
  secret_key_base: 20322d5c0e389a4d4adf7336ff603462f6faf1fdf80671ec60fdde2f64151108a33b5a08637e91024a0f8ed039b9ea01c9f812b7e9204928bc478a132f0b955f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
